### ISSUE TITLE
Safe substitution of 74AHCT with 74LS logic devices?

### ISSUE THREAD

**Issue by elosha** [skiselev/omega#16]
I‘ve read the docs, they suggest the 74AHCT logic family*, but say that 74LS logic could work, while untested.

74LS devices still are widespread among tinkerers. I have a whole box of them, too. And we are building a 4MHz machine. 😉

* Has anyone tried 74LS in meanwhile?

* Which areas of the board are safe to use LS, which are not?

* I would like to learn: Why are the cartridge slot drivers so speed dependent that they even require 74F logic?

Thanks 😊

**Comment by skiselev** [comment]
One person reported building the omega using mostly using 74LS logic, and it worked fine.
* You can use 74LS instead of 74F. The choice of 74F was not related to the speed (although, it doesn't hurt), but to the ability of 74F to sink more current, which is useful in the bus driver applications. Also, new 74F tend to cost less than 74LS
* PAL clock generator (U43) must use 74HCT04. That is if you need PAL clock.
* The sub-slot select logic (U38, U40) is more speed sensitive than other parts, so if possible, I'd recommend using 74AHCT32 for U38, or at least 74F32/74ALS32
* Keep in mind that using 74LS instead of 74HCT/74AHCT will increase the power consumption, so you might need a power supply rated for more current - 5V/3A or more
